config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

 devise_for :admin, controllers: { registrations: 'admin/registrations', sessions: 'admin/sessions' }
 devise_for :customers, controllers: { registrations: 'public/registrations', sessions: 'public/sessions' }

 root to: 'public/homes#top'
  get "/about" =>"public/homes#about"


  scope module: :public do
    resources :items, only: [:index,:show]

    get "/customers/my_page", to: 'customers#show', as: :customer
    get "/customers/unsubscribe", to: 'customers#unsubscribe', as: :customer_unsubscribe
    patch "/customers/withdrawal", to: 'customers#withdrawal', as: :customer_withdrawal
    resource :customers, only: [:edit, :update]

    delete "/cart_items/destroy_all", to: 'cart_items#destroy_all', as: :cart_items_destroy_all
    resources :cart_items, only: [:index, :update, :destroy, :create]

    post "/orders/confirm", to: 'orders#confirm', as: :order_confirm
    get "/orders/thanks", to: 'orders#thanks', as: :order_thanks
    resources :orders, only: [:new, :create, :index, :show]

    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end

  scope module: :admin do
    get 'admin' => "homes#top"
  end

  namespace :admin do
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :order_details, only: [:update]
  end

end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer, optional: true

  def full_address
    '〒' + self.postal_code + ' ' + self.address + ' ' + self.name
  end

  validates :name, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :item
  belongs_to :customer

  def subtotal
    item.with_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def name
    [last_name, first_name].join(' ')
  end

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

  def active_for_authentication?
    super && (is_deleted == false)
  end

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items, dependent: :destroy

end

app/models/item.rb
class Item < ApplicationRecord

  attachment :image
  belongs_to :genre

  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy

  def with_tax_price
      (self.price * 1.1 ).floor
  end

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_details, dependent: :destroy
  accepts_nested_attributes_for :order_details

  enum payment_method: {
    credit_card: 0,
    transfer: 1,
  }

  enum status: {
    waiting_for_payment: 0,
    payment_confirmation: 1,
    cooking: 2,
    preparing_to_ship: 3,
    shipped: 4,
  }

  def full_address
    '〒' + self.postal_code + ' ' + self.address
  end

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :order
  belongs_to :item

  def subtotal
    price * amount
  end

end

app/models/session.rb
class Session < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(@customer.id)
  end

  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :id_active)
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genre = Genre.new
    @genres = Genre.all

  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end


  private
  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  def top
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def index
    @items = Item.page(params[:page]).reverse_order
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end

  private
  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active)
  end

end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::Sessions::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number ])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<h4><%= @customer.name %>さんの会員情報編集</h4>

<%= form_with model:@customer, url: admin_customer_path, local:true do |f| %>

  <table>
    <tr>
      <th>会員ID</th>
      <td><%= @customer.id %></td>
    </tr>
    <tr>
      <th>氏名</th>
      <td><%= f.text_field :last_name %></td>
      <td><%= f.text_field :first_name %></td>
    </tr>
    <tr>
      <th>フリガナ</th>
      <td><%= f.text_field :last_name_kana %></td>
      <td><%= f.text_field :first_name_kana %></td>
    </tr>
    <tr>
      <th>郵便番号</th>
      <td><%= f.text_field :postal_code %></td>
    </tr>
    <tr>
      <th>住所</th>
      <td><%= f.text_field :address, :size=>"60" %></td>
    </tr>
    <tr>
      <th>電話番号</th>
      <td><%= f.text_field :telephone_number %></td>
    </tr>
    <tr>
      <th>メールアドレス</th>
      <td><%= f.text_field :email %></td>
    </tr>
    <tr>
      <th>会員ステータス</th>
      <td>
        <%= f.radio_button :is_active, :true %>
        <%= f.label :is_active, "有効", value: :true %>
        <%= f.radio_button :is_active, :false %>
        <%= f.label :is_active, "退会", value: :false %>
      </td>
    </tr>
  </table>

  <%= f.submit '変更を保存' %>

<% end %>

app/views/admin/customers/index.html.erb
<h4>会員一覧</h4>

<table>
  <thead>
    <tr>
      <th>会員ID</th>
      <th>氏名</th>
      <th>メールアドレス</th>
      <th>ステータス</th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.id %></td>
        <td><%= link_to customer.name, admin_customer_path(customer.id) %></td>
        <td><%= customer.email %></td>
        <td><%= customer.is_active ? '有効' : '退会' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/customers/show.html.erb
<h4><%= @customer.name %>さんの会員詳細</h4>

<table>
  <tr>
    <td>会員ID</td>
    <td><%= @customer.id %></td>
  </tr>
  <tr>
    <td>氏名</td>
    <td><%= @customer.last_name %><%= @customer.first_name %></td>
  </tr>
  <tr>
    <td>フリガナ</td>
    <td><%= @customer.last_name_kana %><%= @customer.first_name_kana %></td>
  </tr>
  <tr>
    <td>郵便番号</td>
    <td><%= @customer.postal_code %></td>
  </tr>
  <tr>
    <td>住所</td>
    <td><%= @customer.address %></td>
  </tr>
  <tr>
    <td>電話番号</td>
    <td><%= @customer.telephone_number %></td>
  </tr>
  <tr>
    <td>メールアドレス</td>
    <td><%= @customer.email %></td>
  </tr>
  <tr>
    <td>会員ステータス</td>
    <td><%= @customer.is_active ? '有効' : '退会' %></td>
  </tr>
</table>

<%= link_to "編集する", edit_admin_customer_path(@customer) %>

app/views/admin/genres/edit.html.erb
<h1>ジャンル編集</h1>

<%= form_with model:@genre, url: admin_genre_path, local:true do |f| %>
  <h4>ジャンル名</h4>
  <%= f.text_field :name %>

  <%= f.submit '変更を保存' %>
<% end %>

app/views/admin/genres/index.html.erb
<h1>ジャンル一覧・追加</h1>

<%= form_with model:@genre, url: admin_genres_path, local:true do |f| %>
  <h4>ジャンル名</h4>
  <%= f.text_field :name %>

  <%= f.submit "新規登録" %>
<% end %>

<tabel>
  <thead>
    <tr>
      <th colspan = "2">ジャンル</th>
    </tr>
  </thead>
  <tbody>
    <tr>
    <% @genres.each do |genre| %>
      <td><%= genre.name %></td>
      <td><%= link_to "編集する", edit_admin_genre_path(genre) %></td>
    </tr>
    <% end %>
  </tbody>
</tabel>

app/views/admin/items/edit.html.erb
<h4>商品編集</h4>

<%= form_with model:@item, url: admin_item_path, local:true do |f| %>

  <table>
    <tr>
      <th>商品画像</th>
      <td><%= f.attachment_field :image %></td>
    </tr>
    <tr>
      <th>商品名</th>
      <td><%= f.text_field :name %></td>
    </tr>
    <tr>
      <th>商品説明</th>
      <td><%= f.text_area :introduction %></td>
    </tr>
    <tr>
      <th>ジャンル</th>
      <td><%= f.collection_select :genre_id, Genre.all, :id, :name %></td>
    </tr>
    <tr>
      <th>税抜価格</th>
      <td><%= f.text_field :price %></td>
      <td>円</td>
    </tr>
    <tr>
      <th>販売ステータス</th>
      <td>
        <%= f.radio_button :is_active, :true %>
        <%= f.label :is_active, "販売中", value: :true %>
        <%= f.radio_button :is_active, :false %>
        <%= f.label :is_active, "販売停止中", value: :false %>
      </td>
    </tr>
  </table>

  <%= f.submit '変更を保存' %>

<% end %>

app/views/admin/items/index.html.erb
<h4>商品一覧</h4>

<table>
  <thead>
    <tr>
      <th>商品ID</th>
      <th>商品名</th>
      <th>税抜価格</th>
      <th>ジャンル</th>
      <th>ステータス</th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.id %></td>
        <td><%= link_to item.name, admin_item_path(item.id) %></td>
        <td><%= item.price.to_s(:delimited) %></td>
        <td><%= item.genre.name %></td>
        <td><%= item.is_active ? '販売中' : '販売停止中' %></td>
      </tr>
    <% end %>
    <%= paginate @items %>
  </tbody>
</table>

app/views/admin/items/new.html.erb
<h4>商品新規登録</h4>
<%= form_with model:@item, url: admin_items_path, local:true do |f| %>
  <p>商品画像</p>
  <%= f.attachment_field :image %>

  <p>商品名</p>
  <%= f.text_field :name, placeholder:"商品名" %>

  <p>商品説明</p>
  <%= f.text_area :introduction, placeholder:"ここに説明文を記述します" %>

  <p>ジャンル</p>
    <%= f.collection_select :genre_id, Genre.all, :id, :name, prompt: "--選択してください--" %>

  <p>税抜価格</p>
  <%= f.text_field :price, placeholder:"1000" %><p>円</p>

  <p>販売ステータス</p>
  <%= f.radio_button :is_active, :true %>
  <%= f.label :is_active, "販売中", value: :true %>
  <%= f.radio_button :is_active, :false %>
  <%= f.label :is_active, "販売停止中", value: :false %>

  <%= f.submit '新規登録' %>
<% end %>

app/views/admin/items/show.html.erb
<h4>商品詳細</h4>

<%= attachment_image_tag @item, :image, :fill, 150, 150 %>

<table>
  <tr>
    <td>商品名</td>
    <td><%= @item.name %></td>
  </tr>
  <tr>
    <td>商品説明</td>
    <td><%= @item.introduction %></td>
  </tr>
  <tr>
    <td>ジャンル</td>
    <td><%= @item.genre.name %></td>
  </tr>
  <tr>
    <td>税込価格(税抜価格)</td>
    <td><%= @item.with_tax_price.to_s(:delimited) %>(<%= @item.price.to_s(:delimited) %>)</td>
  </tr>
  <tr>
    <td>販売ステータス</td>
    <td><%= @item.is_active ? '販売中' : '販売停止中' %></td>
  </tr>
</table>

<%= link_to "編集する", edit_admin_customer_path(@customer) %>